### ISSUE TITLE
Product Images Mapping in Magento

### ISSUE THREAD

**Issue by FabA7** [Agence-DnD/PIMGento-API#4]
Hi DnD,

When I import the products inside Magento and check on the frontend,
there's a display issue with the pictures.

The "image" appears, but both "thumbnail" and "small_image" don't.
![capture2](https://user-images.githubusercontent.com/45561813/51676373-badcb680-1fd6-11e9-8c57-e8f00fb35601.JPG)

Here is my mapping configuration
![capture](https://user-images.githubusercontent.com/45561813/51676411-d21ba400-1fd6-11e9-8627-2c01499a1356.JPG)

I've noticed that if I only map the "image" for import, and then I go in the Magento back-end to activate the thumbnail and small_image manually, it appears correctly on the website.

But I cannot do that for every single product :)
Could you tell me how to fix that please?

Thanks in advance.

BR,
Fab

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

Configuration seems to be OK from your screenshots, we might have to check this issue on our side.

Before that, could you check the following if you have not yet  : 
- Fully reindex Magento
- Clean Image cache
- Clean Magento cache

Also, could you provide us a screenshot of your product images in the backend right after import ?

Thank you very much.

Regards,

**Comment by FabA7** [comment]
@Dnd-Gimix,

• Fully reindex Magento >Done
• Clean Image cache >Done
• Clean Magento cache >Done

I do it usually, but nothing seems to change.

Here is the screenshot after the import
![capture](https://user-images.githubusercontent.com/45561813/51679950-a3a2c680-1fe0-11e9-8d6c-15f1fbe25256.JPG)

Also, I've noticed that it's necessary to manually reindex Magento after the products import to see the products on the frontend, even if the Reindex Data select in the configuration is On.

BR

**Comment by Dnd-Gimix** [comment]
@FabA7 ,

Thank you for your answer.
It seems to be displayed well in the backend, can you switch your admin product page to "Store view" and check if small_image and thumbnail radio button are checked ?

Regards,

**Comment by FabA7** [comment]
![capture](https://user-images.githubusercontent.com/45561813/51680981-92a78480-1fe3-11e9-881d-dfb868cb1295.JPG)
![capture2](https://user-images.githubusercontent.com/45561813/51680988-9509de80-1fe3-11e9-8c89-100a8dee4612.JPG)

It seems to be the same for both.

BR

**Comment by Dnd-Gimix** [comment]
@FabA7 ,

Indeed, thank you for all the details.
We will have a look at your issue soon and provide a fix if necessary.

I will come back to you.

Regards,

**Comment by FabA7** [comment]
Hello Dnd,

Just to bring you more information that maybe could help you,
I've just noticed that, if you define a specific configuration for the store view like this
![capture](https://user-images.githubusercontent.com/45561813/51833000-84fd4200-22f6-11e9-8340-8cc3e5a34c28.JPG)

the picture is well shown on the frontend
![capture2](https://user-images.githubusercontent.com/45561813/51833024-95152180-22f6-11e9-88c4-361f318fdc6a.JPG)

I hope it can help you

Regards,
Fab

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

I hope you are doing well.
This issue has been fixed in the following PR : https://github.com/Agence-DnD/PIMGento-API/pull/5

We will provide a new release for it in the following days.
If you already want to apply the patch, feel free to consult the PR ;)

I will come back to you when the new release is out.

Have a good day !

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

I am glad to inform you that this issue has been resolved and released on the master branch !
Please update your connector, import again your products and reindex your catalog : images should now be displayed correctly on the category page.

Thank you and have a good day ;-)

Regards,

**Comment by FabA7** [comment]
Hello @Dnd-Gimix,

Thanks a lot for your feedback and what you've worked on.
Unfortunately and if I'm not wrong, I still have the problem after updating the connector :(

I'm sure to have updated the Product.php file though.

Regards,
Fab

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

Could you detail me the steps you have followed please ?
Are your products simple or configurable ?

Thanks a lot.
Regards,

**Comment by FabA7** [comment]
Hi @Dnd-Gimix,

Here is the steps :
• Updated the Product.php file in Job folder
• Delete my 2 products
• Import the Products from Pimgento
• Reindex the whole Magento + cache etc

I still have that
![51676373-badcb680-1fd6-11e9-8c57-e8f00fb35601](https://user-images.githubusercontent.com/45561813/52127930-e8a7a800-2633-11e9-8eed-dbf49dc390c1.JPG)

My products are simple.

BR,
Fab

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

Do you have any PHP cache on your server ?
Everything is working well on our side after the last fix.

Regards,

**Comment by FabA7** [comment]
Hi @Dnd-Gimix,

Thank you for your answer, I will try to see for reloading httpd and apache2.
What else could be the problem, any ideas ? You tried on a Magento v1.9.3.10 too ?

BR,
Fab

**Comment by FabA7** [comment]
Okay @Dnd-Gimix,

I reinstalled the whole module, clearing cache and everything.
And it's working I have the pictures :)

Thank you so much for your help ! And sorry for the waste of time.

Best regards,
Fab

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

Perfect ! Glad to hear that.
I'll close this issue as it is resolved.

Thanks again for using PIMGento API, I wish you a good day ;-)

Regards,
